### ISSUE TITLE
Pandora seems to have just broken auth for all the open source apps

### ISSUE THREAD

**Issue by bkw777** [doadin/pandoroid#2]
Pandoroid, Pianobar, and Pithos all suddenly fail auth starting an hour ago. Web page still works.
https://github.com/pithos/pithos/issues/654
https://github.com/PromyLOPh/pianobar/issues/714

**Comment by doadin** [comment]
I just logged in no problem.

**Comment by bkw777** [comment]
With a paid account?
https://community.pandora.com/t5/Desktop/Can-t-Log-In-on-Pithos/m-p/68179#M5300

**Comment by bkw777** [comment]
Working again. Not just me, and not just Pandoroid.
